// Generated by gencpp from file simple_planning/get_plan.msg
// DO NOT EDIT!


#ifndef SIMPLE_PLANNING_MESSAGE_GET_PLAN_H
#define SIMPLE_PLANNING_MESSAGE_GET_PLAN_H

#include <ros/service_traits.h>


#include <simple_planning/get_planRequest.h>
#include <simple_planning/get_planResponse.h>


namespace simple_planning
{

struct get_plan
{

typedef get_planRequest Request;
typedef get_planResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_plan
} // namespace simple_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_planning::get_plan > {
  static const char* value()
  {
    return "ecf2a5b86287c816e8b2cabb479cb7e2";
  }

  static const char* value(const ::simple_planning::get_plan&) { return value(); }
};

template<>
struct DataType< ::simple_planning::get_plan > {
  static const char* value()
  {
    return "simple_planning/get_plan";
  }

  static const char* value(const ::simple_planning::get_plan&) { return value(); }
};


// service_traits::MD5Sum< ::simple_planning::get_planRequest> should match 
// service_traits::MD5Sum< ::simple_planning::get_plan > 
template<>
struct MD5Sum< ::simple_planning::get_planRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_planning::get_plan >::value();
  }
  static const char* value(const ::simple_planning::get_planRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_planning::get_planRequest> should match 
// service_traits::DataType< ::simple_planning::get_plan > 
template<>
struct DataType< ::simple_planning::get_planRequest>
{
  static const char* value()
  {
    return DataType< ::simple_planning::get_plan >::value();
  }
  static const char* value(const ::simple_planning::get_planRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_planning::get_planResponse> should match 
// service_traits::MD5Sum< ::simple_planning::get_plan > 
template<>
struct MD5Sum< ::simple_planning::get_planResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_planning::get_plan >::value();
  }
  static const char* value(const ::simple_planning::get_planResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_planning::get_planResponse> should match 
// service_traits::DataType< ::simple_planning::get_plan > 
template<>
struct DataType< ::simple_planning::get_planResponse>
{
  static const char* value()
  {
    return DataType< ::simple_planning::get_plan >::value();
  }
  static const char* value(const ::simple_planning::get_planResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_PLANNING_MESSAGE_GET_PLAN_H
