// Generated by gencpp from file simple_planning/position.msg
// DO NOT EDIT!


#ifndef SIMPLE_PLANNING_MESSAGE_POSITION_H
#define SIMPLE_PLANNING_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_planning
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : x(0)
    , y(0)
    , yaw(0)  {
    }
  position_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , yaw(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::simple_planning::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_planning::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::simple_planning::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::simple_planning::position > positionPtr;
typedef boost::shared_ptr< ::simple_planning::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_planning::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_planning::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simple_planning': ['/home/endo/bito/src/simple_planning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_planning::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_planning::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_planning::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_planning::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_planning::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_planning::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_planning::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "652061b60d916a0a2696ac0296ce8038";
  }

  static const char* value(const ::simple_planning::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x652061b60d916a0aULL;
  static const uint64_t static_value2 = 0x2696ac0296ce8038ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_planning::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_planning/position";
  }

  static const char* value(const ::simple_planning::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_planning::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
int16 yaw\n\
";
  }

  static const char* value(const ::simple_planning::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_planning::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_planning::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_planning::position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_PLANNING_MESSAGE_POSITION_H
