// Generated by gencpp from file simple_planning/update_goalRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_PLANNING_MESSAGE_UPDATE_GOALREQUEST_H
#define SIMPLE_PLANNING_MESSAGE_UPDATE_GOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <simple_planning/position.h>

namespace simple_planning
{
template <class ContainerAllocator>
struct update_goalRequest_
{
  typedef update_goalRequest_<ContainerAllocator> Type;

  update_goalRequest_()
    : id()
    , goal_pose()  {
    }
  update_goalRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef  ::simple_planning::position_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::simple_planning::update_goalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_planning::update_goalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct update_goalRequest_

typedef ::simple_planning::update_goalRequest_<std::allocator<void> > update_goalRequest;

typedef boost::shared_ptr< ::simple_planning::update_goalRequest > update_goalRequestPtr;
typedef boost::shared_ptr< ::simple_planning::update_goalRequest const> update_goalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_planning::update_goalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_planning::update_goalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simple_planning': ['/home/endo/bito/src/simple_planning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_planning::update_goalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_planning::update_goalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_planning::update_goalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_planning::update_goalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_planning::update_goalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_planning::update_goalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_planning::update_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c3f64fdd204d39a46bf43783756a939";
  }

  static const char* value(const ::simple_planning::update_goalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c3f64fdd204d39aULL;
  static const uint64_t static_value2 = 0x46bf43783756a939ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_planning::update_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_planning/update_goalRequest";
  }

  static const char* value(const ::simple_planning::update_goalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_planning::update_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n\
simple_planning/position goal_pose\n\
\n\
================================================================================\n\
MSG: simple_planning/position\n\
int16 x\n\
int16 y\n\
int16 yaw\n\
";
  }

  static const char* value(const ::simple_planning::update_goalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_planning::update_goalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct update_goalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_planning::update_goalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_planning::update_goalRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::simple_planning::position_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_PLANNING_MESSAGE_UPDATE_GOALREQUEST_H
