// Generated by gencpp from file simple_planning/update_goal.msg
// DO NOT EDIT!


#ifndef SIMPLE_PLANNING_MESSAGE_UPDATE_GOAL_H
#define SIMPLE_PLANNING_MESSAGE_UPDATE_GOAL_H

#include <ros/service_traits.h>


#include <simple_planning/update_goalRequest.h>
#include <simple_planning/update_goalResponse.h>


namespace simple_planning
{

struct update_goal
{

typedef update_goalRequest Request;
typedef update_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct update_goal
} // namespace simple_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_planning::update_goal > {
  static const char* value()
  {
    return "6c3f64fdd204d39a46bf43783756a939";
  }

  static const char* value(const ::simple_planning::update_goal&) { return value(); }
};

template<>
struct DataType< ::simple_planning::update_goal > {
  static const char* value()
  {
    return "simple_planning/update_goal";
  }

  static const char* value(const ::simple_planning::update_goal&) { return value(); }
};


// service_traits::MD5Sum< ::simple_planning::update_goalRequest> should match 
// service_traits::MD5Sum< ::simple_planning::update_goal > 
template<>
struct MD5Sum< ::simple_planning::update_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_planning::update_goal >::value();
  }
  static const char* value(const ::simple_planning::update_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_planning::update_goalRequest> should match 
// service_traits::DataType< ::simple_planning::update_goal > 
template<>
struct DataType< ::simple_planning::update_goalRequest>
{
  static const char* value()
  {
    return DataType< ::simple_planning::update_goal >::value();
  }
  static const char* value(const ::simple_planning::update_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_planning::update_goalResponse> should match 
// service_traits::MD5Sum< ::simple_planning::update_goal > 
template<>
struct MD5Sum< ::simple_planning::update_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_planning::update_goal >::value();
  }
  static const char* value(const ::simple_planning::update_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_planning::update_goalResponse> should match 
// service_traits::DataType< ::simple_planning::update_goal > 
template<>
struct DataType< ::simple_planning::update_goalResponse>
{
  static const char* value()
  {
    return DataType< ::simple_planning::update_goal >::value();
  }
  static const char* value(const ::simple_planning::update_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_PLANNING_MESSAGE_UPDATE_GOAL_H
